# Generated by Django 4.0.3 on 2022-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
