# Generated by Django 3.2 on 2022-06-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20220617_0147'),
        ('institute', '0001_initial'),
        ('course', '0004_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.grade', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institute.institute', verbose_name='آموزشگاه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='course',
            name='participation',
            field=models.ManyToManyField(related_name='part', to='student.Student'),
        ),
    ]
