# Generated by Django 4.0.3 on 2022-04-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_master_institute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="master",
            name="institute",
        ),
    ]
