# Generated by Django 4.0.3 on 2022-04-21 13:12

from django.db import migrations, models

import extenstion.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("image", models.ImageField(upload_to=extenstion.utils.get_file_path)),
            ],
        ),
    ]
