# Generated by Django 3.2 on 2022-06-16 21:17

from django.db import migrations, models
import extenstion.utils


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to=extenstion.utils.get_file_path),
        ),
    ]
