# Generated by Django 4.0.3 on 2022-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_remove_grade_parent_remove_grade_institute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="major",
            name="grade",
            field=models.ManyToManyField(to="student.grade"),
        ),
    ]
