# Generated by Django 4.0.3 on 2022-04-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_major_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="grade",
        ),
        migrations.AddField(
            model_name="grade",
            name="major",
            field=models.ManyToManyField(to="student.major"),
        ),
    ]
