# Generated by Django 4.0.3 on 2022-04-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_major_grade_grade_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='major',
        ),
        migrations.RemoveField(
            model_name='major',
            name='institute',
        ),
        migrations.AddField(
            model_name='major',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.grade'),
        ),
    ]
