# Generated by Django 4.0.3 on 2022-04-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_grade_institute_remove_grade_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='major',
            new_name='grade',
        ),
    ]
