# Generated by Django 4.0.3 on 2022-05-05 23:35

from django.db import migrations, models
import extenstion.utils


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to=extenstion.utils.get_file_path),
        ),
    ]
