# Generated by Django 3.2 on 2022-06-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone_numer',
            field=models.CharField(max_length=11),
        ),
    ]
