# Generated by Django 3.2 on 2022-06-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20220617_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
