# Generated by Django 3.2 on 2022-06-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
        ('student', '0016_auto_20220617_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.institute'),
        ),
    ]
