# Generated by Django 3.2 on 2022-06-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_installment_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
