# Generated by Django 3.2 on 2022-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
