# Generated by Django 3.2 on 2022-07-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20220716_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
    ]
