# Generated by Django 3.2 on 2022-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicyear', '0003_remove_academicyear_student'),
        ('student', '0023_delete_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ManyToManyField(related_name='students', to='academicyear.AcademicYear'),
        ),
    ]
