# Generated by Django 3.2 on 2022-07-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicyear', '0003_remove_academicyear_student'),
        ('student', '0024_student_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='academicyear.academicyear'),
        ),
    ]
