# Generated by Django 3.2 on 2022-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0023_delete_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('student', models.ManyToManyField(related_name='academic_year', to='student.Student')),
            ],
        ),
    ]
