# Generated by Django 3.2 on 2022-07-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicyear', '0002_academicyear_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='student',
        ),
    ]
