# Generated by Django 4.0.3 on 2022-04-16 21:57

import ckeditor.fields
from django.db import migrations, models

import extenstion.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("logo", models.ImageField(upload_to=extenstion.utils.get_file_path)),
                ("description", ckeditor.fields.RichTextField()),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
